/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "Gpio.h"
#include "stm32f103x6"
Gpio_PinConfig_t PA1={.mode=GPIO_INPUT_Analog_PU,.output_speed=GPIO_OUTPUT_MODE_10MHz,.pinNumber=GPIO_PIN1};
Gpio_PinConfig_t PA13={.mode=GPIO_INPUT_Analog_PD,.output_speed=GPIO_OUTPUT_MODE_10MHz,.pinNumber=GPIO_PIN13};
Gpio_PinConfig_t PB1={.mode=GPIO_OUTPUT_Push_Pull,.output_speed=GPIO_OUTPUT_MODE_10MHz,.pinNumber=GPIO_PIN1};
Gpio_PinConfig_t PB13={.mode=GPIO_OUTPUT_Push_Pull,.output_speed=GPIO_OUTPUT_MODE_10MHz,.pinNumber=GPIO_PIN13};
int main(void)
{
	RCC_GPIOA_EN_CLK();
	RCC_GPIOB_EN_CLK();
	MCAL_Gpio_Init(GPIOA,&PA1);
	MCAL_Gpio_Init(GPIOA,&PA13);
	MCAL_Gpio_Init(GPIOB,&PB1);
	MCAL_Gpio_Init(GPIOB,&PB13);
    /* Loop forever */
	while (1)
	    {
	        // Check if PA1 is pressed (active low)
	        if (MCAL_Gpio_ReadPin(GPIOA, GPIO_PIN1)== 0)
	        {
	            MCAL_Gpio_TogglePin(GPIOB, GPIO_PIN1); // Toggle PB1 on PA1 press
	            while (MCAL_Gpio_ReadPin(GPIOA, GPIO_PIN1)== 0); // Wait until PA1 is released
	        }

	        // Check if PA13 is pressed (active high)
	        if(MCAL_Gpio_ReadPin(GPIOA, GPIO_PIN13)== 1)
	        {
	            MCAL_Gpio_TogglePin(GPIOB, GPIO_PIN13); // Toggle PB1 on PA1 press
	        }
	        // Simple debounce delay
	        for (int i = 0; i < 10000; ++i);
	    }
}
