/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
typedef volatile unsigned int vu32;
#define RCC_BASE 	  (*(vu32*)0x40021000)
#define RCC_APB2ENR   (*(vu32*)(0x18+RCC_BASE))
#define IOPAEN		  (1<<2)
#define GPIOA_BASE 	  (*(vu32*)0x40010800)
#define GPIOA_CRH	  (*(vu32*)(0x04+GPIOA_BASE))
#define GPIOA_ODR	  (*(vu32*)(0x0c+GPIOA_BASE))
#define pin13   	  (1<<13)

void pinA13_init()
{
	RCC_APB2ENR |= IOPAEN;
	GPIOA_CRH   &= ~(0xf<<20);
	GPIOA_CRH 	|= (0b10<<20);
	GPIOA_CRH 	|= (0b01<<22);
}

int main(void)
{
	pinA13_init();
    while(1)
    {
    	GPIOA_ODR |= pin13;
    	for(int i=0;i<5000;++i);
    	GPIOA_ODR &= ~pin13;
    	for(int i=0;i<5000;++i);
    }
}
