/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "HAL_layer/LCD/lcd.h"
#include "HAL_layer/Keypad/Keypad.h"
volatile char value='\0';
int main(void)
{
	RCC_GPIOA_EN_CLK();
	RCC_GPIOB_EN_CLK();
	HAL_LCD_INIT();
	HAL_KEYPAD_INIT();
	HAL_LCD_WRITE_STRING("HESHAM ELNGAR");
	delay_ms(500);
	HAL_LCD_CLEAR_SCREEN();
	HAL_LCD_WRITE_STRING("my number is:");
	HAL_LCD_GOTO_XY(2, 1);
    /* Loop forever */
	while (1)
	    {
		while(value=='\0')
		value=HAL_KEYPAD_GET_KEY();
		HAL_LCD_WRITE_CHAR(value);
		value='\0';
}
